export const aGroup = {
  katakana: { ア: "a", イ: "i", ウ: "u", エ: "e", オ: "o" },
  hiragana: { あ: "a", い: "i", う: "u", え: "e", お: "o" },
};
export const kaGroup = {
  katakana: {
    カ: "ka",
    キ: "ki",
    ク: "ku",
    ケ: "ke",
    コ: "ko",
    ガ: "ga",
    ギ: "gi",
    グ: "gu",
    ゲ: "ge",
    ゴ: "go",
    キャ: "kya",
    キュ: "kyu",
    キョ: "kyo",
    ギャ: "gya",
    ギュ: "gyu",
    ギョ: "gyo",
  },
  hiragana: {
    か: "ka",
    き: "ki",
    く: "ku",
    け: "ke",
    こ: "ko",
    が: "ga",
    ぎ: "gi",
    ぐ: "gu",
    げ: "ge",
    ご: "go",
    きゃ: "kya",
    きゅ: "kyu",
    きょ: "kyo",
    ぎゃ: "gya",
    ぎゅ: "gyu",
    ぎょ: "gyo",
  },
};
export const saGroup = {
  katakana: {
    サ: "sa",
    シ: "shi",
    ス: "su",
    セ: "se",
    ソ: "so",
    ザ: "za",
    ジ: "ji",
    ズ: "zu",
    ゼ: "ze",
    ゾ: "zo",
    ジャ: "ja",
    ジュ: "ju",
    ジェ: "je",
    ジョ: "jo",
    シャ: "sha",
    シュ: "shu",
    シェ: "she",
    ショ: "sho",
  },
  hiragana: {
    さ: "sa",
    し: "shi",
    す: "su",
    せ: "se",
    そ: "so",
    ざ: "za",
    じ: "ji",
    ず: "zu",
    ぜ: "ze",
    ぞ: "zo",
    じゃ: "ja",
    じゅ: "ju",
    じぇ: "je",
    じょ: "jo",
    しゃ: "sha",
    しゅ: "shu",
    しぇ: "she",
    しょ: "sho",
  },
};
export const taGroup = {
  katakana: {
    タ: "ta",
    チ: "chi",
    ツ: "tsu",
    テ: "te",
    ト: "to",
    ダ: "da",
    ヂ: "ji",
    ヅ: "zu",
    デ: "de",
    ド: "do",
    チャ: "cha",
    チュ: "chu",
    チェ: "che",
    チョ: "cho",
    ヂャ: "ja",
    ヂュ: "ju",
    ヂェ: "je",
    ヂョ: "jo",
  },
  hiragana: {
    た: "ta",
    ち: "chi",
    つ: "tsu",
    て: "te",
    と: "to",
    だ: "da",
    ぢ: "ji",
    づ: "zu",
    で: "de",
    ど: "do",
    ちゃ: "cha",
    ちゅ: "chu",
    ちぇ: "che",
    ちょ: "cho",
    ぢゃ: "ja",
    ぢゅ: "ju",
    ぢぇ: "je",
    ぢょ: "jo",
  },
};
export const naGroup = {
  katakana: {
    ナ: "na",
    ニ: "ni",
    ヌ: "nu",
    ネ: "ne",
    ノ: "no",
    ニャ: "nya",
    ニュ: "nyu",
    ニョ: "nyo",
  },
  hiragana: {
    な: "na",
    に: "ni",
    ぬ: "nu",
    ね: "ne",
    の: "no",
    にゃ: "nya",
    にゅ: "nyu",
    にょ: "nyo",
  },
};
export const haGroup = {
  katakana: {
    ハ: "ha",
    ヒ: "hi",
    フ: "fu",
    ヘ: "he",
    ホ: "ho",
    バ: "ba",
    ビ: "bi",
    ブ: "bu",
    ベ: "be",
    ボ: "bo",
    パ: "pa",
    ピ: "pi",
    プ: "pu",
    ペ: "pe",
    ポ: "po",
    ヒャ: "hya",
    ヒュ: "hyu",
    ヒョ: "hyo",
    ビャ: "bya",
    ビュ: "byu",
    ビョ: "byo",
    ピャ: "pya",
    ピュ: "pyu",
    ピョ: "pyo",
  },
  hiragana: {
    は: "ha",
    ひ: "hi",
    ふ: "fu",
    へ: "he",
    ほ: "ho",
    ば: "ba",
    び: "bi",
    ぶ: "bu",
    べ: "be",
    ぼ: "bo",
    ぱ: "pa",
    ぴ: "pi",
    ぷ: "pu",
    ぺ: "pe",
    ぽ: "po",
    ひゃ: "hya",
    ひゅ: "hyu",
    ひょ: "hyo",
    びゃ: "bya",
    びゅ: "byu",
    びょ: "byo",
    ぴゃ: "pya",
    ぴゅ: "pyu",
    ぴょ: "pyo",
  },
};
export const maGroup = {
  katakana: {
    マ: "ma",
    ミ: "mi",
    ム: "mu",
    メ: "me",
    モ: "mo",
    ミャ: "mya",
    ミュ: "myu",
    ミョ: "myo",
  },
  hiragana: {
    ま: "ma",
    み: "mi",
    む: "mu",
    め: "me",
    も: "mo",
    みゃ: "mya",
    みゅ: "myu",
    みょ: "myo",
  },
};
export const yaGroup = {
  katakana: { ヤ: "ya", ユ: "yu", ヨ: "yo" },
  hiragana: { や: "ya", ゆ: "yu", よ: "yo" },
};
export const raGroup = {
  katakana: {
    ラ: "ra",
    リ: "ri",
    ル: "ru",
    レ: "re",
    ロ: "ro",
    リャ: "rya",
    リュ: "ryu",
    リョ: "ryo",
  },
  hiragana: {
    ら: "ra",
    り: "ri",
    る: "ru",
    れ: "re",
    ろ: "ro",
    りゃ: "rya",
    りゅ: "ryu",
    りょ: "ryo",
  },
};
export const waGroup = {
  katakana: { ワ: "wa", ヲ: "wo" },
  hiragana: { わ: "wa", を: "wo" },
};

export const hiraganaGrouped = {
  aGroup: aGroup.hiragana,
  kaGroup: kaGroup.hiragana,
  saGroup: saGroup.hiragana,
  taGroup: taGroup.hiragana,
  naGroup: naGroup.hiragana,
  haGroup: haGroup.hiragana,
  maGroup: maGroup.hiragana,
  yaGroup: yaGroup.hiragana,
  raGroup: raGroup.hiragana,
  waGroup: waGroup.hiragana,
};

export const katakanaGrouped = {
  aGroup: aGroup.katakana,
  kaGroup: kaGroup.katakana,
  saGroup: saGroup.katakana,
  taGroup: taGroup.katakana,
  naGroup: naGroup.katakana,
  haGroup: haGroup.katakana,
  maGroup: maGroup.katakana,
  yaGroup: yaGroup.katakana,
  raGroup: raGroup.katakana,
  waGroup: waGroup.katakana,
};
