import { LevelChoiceType } from "./types";

export const hiraganaAndKatakanaLevelChoices: LevelChoiceType[] = [
  {
    characterKatakana: "ア",
    characterHiragana: "あ",
    name: `"A" Set Characters`,
    charactersHiragana: ["あ", "い", "う", "え", "お"],
    charactersKatakana: ["ア", "イ", "ウ", "エ", "オ"],
    href: "a-set",
  },
  {
    characterKatakana: "カ",
    characterHiragana: "か",
    name: `"Ka" Set Characters`,
    charactersHiragana: ["か", "き", "く", "け", "こ"],
    charactersKatakana: ["カ", "キ", "ク", "ケ", "コ"],
    href: "ka-set",
  },
  {
    characterKatakana: "サ",
    characterHiragana: "さ",
    name: `"Sa" Set Characters`,
    charactersHiragana: ["さ", "し", "す", "せ", "そ"],
    charactersKatakana: ["サ", "シ", "ス", "セ", "ソ"],
    href: "sa-set",
  },
  {
    characterKatakana: "タ",
    characterHiragana: "た",
    name: `"Ta" Set Characters`,
    charactersHiragana: ["た", "ち", "つ", "て", "と"],
    charactersKatakana: ["タ", "チ", "ツ", "テ", "ト"],
    href: "ta-set",
  },
  {
    characterKatakana: "ナ",
    characterHiragana: "な",
    name: `"Na" Set Characters`,
    charactersHiragana: ["な", "に", "ぬ", "ね", "の"],
    charactersKatakana: ["ナ", "ニ", "ヌ", "ネ", "ノ"],
    href: "na-set",
  },
  {
    characterKatakana: "ハ",
    characterHiragana: "は",
    name: `"Ha" Set Characters`,
    charactersHiragana: ["は", "ひ", "ふ", "へ", "ほ"],
    charactersKatakana: ["ハ", "ヒ", "フ", "ヘ", "ホ"],
    href: "ha-set",
  },
  {
    characterKatakana: "マ",
    characterHiragana: "ま",
    name: `"Ma" Set Characters`,
    charactersHiragana: ["ま", "み", "む", "め", "も"],
    charactersKatakana: ["マ", "ミ", "ム", "メ", "モ"],
    href: "ma-set",
  },
  {
    characterKatakana: "ヤ",
    characterHiragana: "や",
    name: `"Ya" Set Characters`,
    charactersHiragana: ["や", "ゆ", "よ"],
    charactersKatakana: ["ヤ", "ユ", "ヨ"],
    href: "ya-set",
  },
  {
    characterKatakana: "ラ",
    characterHiragana: "ら",
    name: `"Ra" Set Characters`,
    charactersHiragana: ["ら", "り", "る", "れ", "ろ"],
    charactersKatakana: ["ラ", "リ", "ル", "レ", "ロ"],
    href: "ra-set",
  },
  {
    characterKatakana: "ワ",
    characterHiragana: "わ",
    name: `"Wa" & "N" Set Characters`,
    charactersHiragana: ["わ", "を", "ん"],
    charactersKatakana: ["ワ", "ヲ", "ン"],
    href: "wa-set",
  },
  {
    characterKatakana: "ガ",
    characterHiragana: "が",
    name: "Dakuten Set Characters",
    charactersHiragana: [
      "が",
      "ぎ",
      "ぐ",
      "げ",
      "ご",
      "ざ",
      "じ",
      "ず",
      "ぜ",
      "ぞ",
      "だ",
      "ぢ",
      "づ",
      "で",
      "ど",
      "ば",
      "び",
      "ぶ",
      "べ",
      "ぼ",
      "ぱ",
      "ぴ",
      "ぷ",
      "ぺ",
      "ぽ",
    ],
    charactersKatakana: [
      "ガ",
      "ギ",
      "グ",
      "ゲ",
      "ゴ",
      "ザ",
      "ジ",
      "ズ",
      "ゼ",
      "ゾ",
      "ダ",
      "ヂ",
      "ヅ",
      "デ",
      "ド",
      "バ",
      "ビ",
      "ブ",
      "ベ",
      "ボ",
      "パ",
      "ピ",
      "プ",
      "ペ",
      "ポ",
    ],
    href: "dakuten-set",
  },
  {
    characterKatakana: "ヒャ",
    characterHiragana: "ひゃ",
    name: "Combination Set Characters",
    charactersHiragana: [
      "きゃ",
      "きゅ",
      "きょ",
      "ぎゃ",
      "ぎゅ",
      "ぎょ",
      "にゃ",
      "にゅ",
      "にょ",
      "ひゃ",
      "ひゅ",
      "ひょ",
      "びゃ",
      "びゅ",
      "びょ",
      "ぴゃ",
      "ぴゅ",
      "ぴょ",
      "みゃ",
      "みゅ",
      "みょ",
      "りゃ",
      "りゅ",
      "りょ",
      "じゃ",
      "じゅ",
      "じぇ",
      "じょ",
      "しゃ",
      "しゅ",
      "しぇ",
      "しょ",
      "ちゃ",
      "ちゅ",
      "ちぇ",
      "ちょ",
      "ぢゃ",
      "ぢゅ",
      "ぢぇ",
      "ぢょ",
    ],
    charactersKatakana: [
      "キャ",
      "キュ",
      "キョ",
      "ギャ",
      "ギュ",
      "ギョ",
      "ニャ",
      "ニュ",
      "ニョ",
      "ヒャ",
      "ヒュ",
      "ヒョ",
      "ビャ",
      "ビュ",
      "ビョ",
      "ピャ",
      "ピュ",
      "ピョ",
      "ミャ",
      "ミュ",
      "ミョ",
      "リャ",
      "リュ",
      "リョ",
      "ジャ",
      "ジュ",
      "ジェ",
      "ジョ",
      "シャ",
      "シュ",
      "シェ",
      "ショ",
      "チャ",
      "チュ",
      "チェ",
      "チョ",
      "ヂャ",
      "ヂュ",
      "ヂェ",
      "ヂョ",
    ],
    href: "combination-set",
  },
];
