const countries = [
  {
    "Country (Indonesian)": "Amerika Serikat",
    "Country (Japanese)": "アメリカ",
    "Country (Kanji)": "",
    "Person (Japanese)": "アメリカ人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Inggris",
    "Country (Japanese)": "イギリス",
    "Country (Kanji)": "",
    "Person (Japanese)": "イギリス人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Italia",
    "Country (Japanese)": "イタリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "イタリア人",
    "Language (Japanese)": "イタリア語",
  },
  {
    "Country (Indonesian)": "Iran",
    "Country (Japanese)": "イラン",
    "Country (Kanji)": "",
    "Person (Japanese)": "イラン人",
    "Language (Japanese)": "ペルシア語",
  },
  {
    "Country (Indonesian)": "India",
    "Country (Japanese)": "インド",
    "Country (Kanji)": "",
    "Person (Japanese)": "インド人",
    "Language (Japanese)": "ヒンディー語",
  },
  {
    "Country (Indonesian)": "Indonesia",
    "Country (Japanese)": "インドネシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "インドネシア人",
    "Language (Japanese)": "インドネシア語",
  },
  {
    "Country (Indonesian)": "Mesir",
    "Country (Japanese)": "エジプト",
    "Country (Kanji)": "",
    "Person (Japanese)": "エジプト人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Australia",
    "Country (Japanese)": "オーストラリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "オーストラリア人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Kanada",
    "Country (Japanese)": "カナダ",
    "Country (Kanji)": "",
    "Person (Japanese)": "カナダ人",
    "Language (Japanese)": "えいご, フランス語",
  },
  {
    "Country (Indonesian)": "Korea Selatan",
    "Country (Japanese)": "かんこく",
    "Country (Kanji)": "韓国",
    "Person (Japanese)": "かんこく人",
    "Language (Japanese)": "かんこく語",
  },
  {
    "Country (Indonesian)": "Arab Saudi",
    "Country (Japanese)": "サウジアラビア",
    "Country (Kanji)": "",
    "Person (Japanese)": "サウジアラビア人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Singapura",
    "Country (Japanese)": "シンガポール",
    "Country (Kanji)": "",
    "Person (Japanese)": "シンガポール人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Spanyol",
    "Country (Japanese)": "スペイン",
    "Country (Kanji)": "",
    "Person (Japanese)": "スペイン人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Thailand",
    "Country (Japanese)": "タイ",
    "Country (Kanji)": "",
    "Person (Japanese)": "タイ人",
    "Language (Japanese)": "タイ語",
  },
  {
    "Country (Indonesian)": "Cina",
    "Country (Japanese)": "ちゅうごく",
    "Country (Kanji)": "中国",
    "Person (Japanese)": "ちゅうごく人",
    "Language (Japanese)": "ちゅうごく語",
  },
  {
    "Country (Indonesian)": "Jerman",
    "Country (Japanese)": "ドイツ",
    "Country (Kanji)": "",
    "Person (Japanese)": "ドイツ人",
    "Language (Japanese)": "ドイツ語",
  },
  {
    "Country (Indonesian)": "Jepang",
    "Country (Japanese)": "にほん",
    "Country (Kanji)": "日本",
    "Person (Japanese)": "にほん人",
    "Language (Japanese)": "にほんご",
  },
  {
    "Country (Indonesian)": "Perancis",
    "Country (Japanese)": "フランス",
    "Country (Kanji)": "",
    "Person (Japanese)": "フランス人",
    "Language (Japanese)": "フランス語",
  },
  {
    "Country (Indonesian)": "Filipina",
    "Country (Japanese)": "フィリピン",
    "Country (Kanji)": "",
    "Person (Japanese)": "フィリピン人",
    "Language (Japanese)": "フィリピノ語",
  },
  {
    "Country (Indonesian)": "Brazil",
    "Country (Japanese)": "ブラジル",
    "Country (Kanji)": "",
    "Person (Japanese)": "ブラジル人",
    "Language (Japanese)": "ポルトガル語",
  },
  {
    "Country (Indonesian)": "Vietnam",
    "Country (Japanese)": "ベトナム",
    "Country (Kanji)": "",
    "Person (Japanese)": "ベトナム人",
    "Language (Japanese)": "ベトナム語",
  },
  {
    "Country (Indonesian)": "Malaysia",
    "Country (Japanese)": "マレーシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "マレーシア人",
    "Language (Japanese)": "マレーシア語",
  },
  {
    "Country (Indonesian)": "Meksiko",
    "Country (Japanese)": "メキシコ",
    "Country (Kanji)": "",
    "Person (Japanese)": "メキシコ人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Rusia",
    "Country (Japanese)": "ロシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "ロシア人",
    "Language (Japanese)": "ロシア語",
  },
];

export const occupations = [
  {
    romaji: "kyoushi",
    furigana: "きょうし",
    kanji: "教師",
    meaning: "Guru, Dosen",
  },
  {
    romaji: "gakusei",
    furigana: "がくせい",
    kanji: "学生",
    meaning: "Mahasiswa",
  },
  {
    romaji: "kaishain",
    furigana: "かいしゃいん",
    kanji: "会社員",
    meaning: "Karyawan Perusahaan",
  },
  {
    romaji: "ginkouin",
    furigana: "ぎんこういん",
    kanji: "銀行員",
    meaning: "Pegawai Bank",
  },
  {
    romaji: "isha",
    furigana: "いしゃ",
    kanji: "医者",
    meaning: "Dokter",
  },
  {
    romaji: "kenkyuusha",
    furigana: "けんきゅうしゃ",
    kanji: "研究者",
    meaning: "Peneliti",
  },
  {
    romaji: "engi-nia",
    furigana: "エンジニア",
    kanji: "",
    meaning: "Insinyur, Teknisi",
  },
  {
    romaji: "shufu",
    furigana: "しゅふ",
    kanji: "主婦",
    meaning: "Ibu Rumah Tangga",
  },
  {
    romaji: "kōmuin",
    furigana: "こうむいん",
    kanji: "公務員",
    meaning: "Pegawai Negeri Sipil (PNS)",
  },
  {
    romaji: "bengoshi",
    furigana: "べんごし",
    kanji: "弁護士",
    meaning: "Pengacara",
  },
  {
    romaji: "kangoshi",
    furigana: "かんごし",
    kanji: "看護師",
    meaning: "Perawat",
  },
  {
    romaji: "nōka",
    furigana: "のうか",
    kanji: "農家",
    meaning: "Petani",
  },
  {
    romaji: "sekkeishi",
    furigana: "せっけいし",
    kanji: "設計士",
    meaning: "Arsitek, Desainer",
  },
  {
    romaji: "keisatsukan",
    furigana: "けいさつかん",
    kanji: "警察官",
    meaning: "Polisi",
  },
  {
    romaji: "ten'in",
    furigana: "てんいん",
    kanji: "店員",
    meaning: "Pegawai Toko",
  },
  {
    romaji: "desainā",
    furigana: "デザイナー",
    kanji: "",
    meaning: "Perancang, Desainer",
  },
  {
    romaji: "haiyuu",
    furigana: "はいゆう",
    kanji: "俳優",
    meaning: "Aktor, Aktris",
  },
  {
    romaji: "sensei",
    furigana: "せんせい",
    kanji: "先生",
    meaning: "Guru (digunakan untuk memanggil/merujuk)",
  },
  {
    romaji: "sakka",
    furigana: "さっか",
    kanji: "作家",
    meaning: "Penulis",
  },
  {
    romaji: "unten-shu",
    furigana: "うんてんしゅ",
    kanji: "運転手",
    meaning: "Pengemudi, Sopir",
  },
  {
    romaji: "ryōrinin",
    furigana: "りょうりにん",
    kanji: "料理人",
    meaning: "Juru Masak, Koki",
  },
  {
    romaji: "gaka",
    furigana: "がか",
    kanji: "画家",
    meaning: "Pelukis",
  },
  {
    romaji: "supōtsu senshu",
    furigana: "スポーツせんしゅ",
    kanji: "スポーツ選手",
    meaning: "Atlet, Pemain Olahraga",
  },
  {
    romaji: "shōbōshi",
    furigana: "しょうぼうし",
    kanji: "消防士",
    meaning: "Petugas Pemadam Kebakaran",
  },
];
