const countries = [
  {
    "Country (Indonesian)": "Amerika Serikat",
    "Country (Japanese)": "アメリカ",
    "Country (Kanji)": "",
    "Person (Japanese)": "アメリカ人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Inggris",
    "Country (Japanese)": "イギリス",
    "Country (Kanji)": "",
    "Person (Japanese)": "イギリス人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Italia",
    "Country (Japanese)": "イタリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "イタリア人",
    "Language (Japanese)": "イタリア語",
  },
  {
    "Country (Indonesian)": "Iran",
    "Country (Japanese)": "イラン",
    "Country (Kanji)": "",
    "Person (Japanese)": "イラン人",
    "Language (Japanese)": "ペルシア語",
  },
  {
    "Country (Indonesian)": "India",
    "Country (Japanese)": "インド",
    "Country (Kanji)": "",
    "Person (Japanese)": "インド人",
    "Language (Japanese)": "ヒンディー語",
  },
  {
    "Country (Indonesian)": "Indonesia",
    "Country (Japanese)": "インドネシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "インドネシア人",
    "Language (Japanese)": "インドネシア語",
  },
  {
    "Country (Indonesian)": "Mesir",
    "Country (Japanese)": "エジプト",
    "Country (Kanji)": "",
    "Person (Japanese)": "エジプト人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Australia",
    "Country (Japanese)": "オーストラリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "オーストラリア人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Kanada",
    "Country (Japanese)": "カナダ",
    "Country (Kanji)": "",
    "Person (Japanese)": "カナダ人",
    "Language (Japanese)": "えいご, フランス語",
  },
  {
    "Country (Indonesian)": "Korea Selatan",
    "Country (Japanese)": "かんこく",
    "Country (Kanji)": "韓国",
    "Person (Japanese)": "かんこく人",
    "Language (Japanese)": "かんこく語",
  },
  {
    "Country (Indonesian)": "Arab Saudi",
    "Country (Japanese)": "サウジアラビア",
    "Country (Kanji)": "",
    "Person (Japanese)": "サウジアラビア人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Singapura",
    "Country (Japanese)": "シンガポール",
    "Country (Kanji)": "",
    "Person (Japanese)": "シンガポール人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Spanyol",
    "Country (Japanese)": "スペイン",
    "Country (Kanji)": "",
    "Person (Japanese)": "スペイン人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Thailand",
    "Country (Japanese)": "タイ",
    "Country (Kanji)": "",
    "Person (Japanese)": "タイ人",
    "Language (Japanese)": "タイ語",
  },
  {
    "Country (Indonesian)": "Cina",
    "Country (Japanese)": "ちゅうごく",
    "Country (Kanji)": "中国",
    "Person (Japanese)": "ちゅうごく人",
    "Language (Japanese)": "ちゅうごく語",
  },
  {
    "Country (Indonesian)": "Jerman",
    "Country (Japanese)": "ドイツ",
    "Country (Kanji)": "",
    "Person (Japanese)": "ドイツ人",
    "Language (Japanese)": "ドイツ語",
  },
  {
    "Country (Indonesian)": "Jepang",
    "Country (Japanese)": "にほん",
    "Country (Kanji)": "日本",
    "Person (Japanese)": "にほん人",
    "Language (Japanese)": "にほんご",
  },
  {
    "Country (Indonesian)": "Perancis",
    "Country (Japanese)": "フランス",
    "Country (Kanji)": "",
    "Person (Japanese)": "フランス人",
    "Language (Japanese)": "フランス語",
  },
  {
    "Country (Indonesian)": "Filipina",
    "Country (Japanese)": "フィリピン",
    "Country (Kanji)": "",
    "Person (Japanese)": "フィリピン人",
    "Language (Japanese)": "フィリピノ語",
  },
  {
    "Country (Indonesian)": "Brazil",
    "Country (Japanese)": "ブラジル",
    "Country (Kanji)": "",
    "Person (Japanese)": "ブラジル人",
    "Language (Japanese)": "ポルトガル語",
  },
  {
    "Country (Indonesian)": "Vietnam",
    "Country (Japanese)": "ベトナム",
    "Country (Kanji)": "",
    "Person (Japanese)": "ベトナム人",
    "Language (Japanese)": "ベトナム語",
  },
  {
    "Country (Indonesian)": "Malaysia",
    "Country (Japanese)": "マレーシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "マレーシア人",
    "Language (Japanese)": "マレーシア語",
  },
  {
    "Country (Indonesian)": "Meksiko",
    "Country (Japanese)": "メキシコ",
    "Country (Kanji)": "",
    "Person (Japanese)": "メキシコ人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Rusia",
    "Country (Japanese)": "ロシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "ロシア人",
    "Language (Japanese)": "ロシア語",
  },
];

export const occupations = [
  {
    romaji: "kyoushi",
    furigana: "きょうし",
    kanji: "教師",
    meaning: "Guru, Dosen (sebagai profesi)",
    indonesian_translation_options: ["Guru", "Dosen"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gakusei",
    furigana: "がくせい",
    kanji: "学生",
    meaning: "Mahasiswa, Pelajar",
    indonesian_translation_options: ["Mahasiswa", "Pelajar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaishain",
    furigana: "かいしゃいん",
    kanji: "会社員",
    meaning: "Karyawan Perusahaan",
    indonesian_translation_options: ["Karyawan Perusahaan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ginkouin",
    furigana: "ぎんこういん",
    kanji: "銀行員",
    meaning: "Pegawai Bank",
    indonesian_translation_options: ["Pegawai Bank"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "isha",
    furigana: "いしゃ",
    kanji: "医者",
    meaning: "Dokter",
    indonesian_translation_options: ["Dokter"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kenkyuusha",
    furigana: "けんきゅうしゃ",
    kanji: "研究者",
    meaning: "Peneliti",
    indonesian_translation_options: ["Peneliti"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shufu",
    furigana: "しゅふ",
    kanji: "主婦",
    meaning: "Ibu Rumah Tangga",
    indonesian_translation_options: ["Ibu Rumah Tangga"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kōmuin",
    furigana: "こうむいん",
    kanji: "公務員",
    meaning: "Pegawai Negeri Sipil (PNS)",
    indonesian_translation_options: ["Pegawai Negeri Sipil"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "bengoshi",
    furigana: "べんごし",
    kanji: "弁護士",
    meaning: "Pengacara",
    indonesian_translation_options: ["Pengacara"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kangoshi",
    furigana: "かんごし",
    kanji: "看護師",
    meaning: "Perawat",
    indonesian_translation_options: ["Perawat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sekkeishi",
    furigana: "せっけいし",
    kanji: "設計士",
    meaning: "Arsitek, Desainer (bidang bangunan/teknik)",
    indonesian_translation_options: ["Arsitek", "Desainer"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "keisatsukan",
    furigana: "けいさつかん",
    kanji: "警察官",
    meaning: "Polisi",
    indonesian_translation_options: ["Polisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ten'in",
    furigana: "てんいん",
    kanji: "店員",
    meaning: "Pegawai Toko",
    indonesian_translation_options: ["Pegawai Toko"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "unten-shu",
    furigana: "うんてんしゅ",
    kanji: "運転手",
    meaning: "Pengemudi, Sopir",
    indonesian_translation_options: ["Pengemudi", "Sopir"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ryōrinin",
    furigana: "りょうりにん",
    kanji: "料理人",
    meaning: "Juru Masak, Koki",
    indonesian_translation_options: ["Juru Masak", "Koki"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shōbōshi",
    furigana: "しょうぼうし",
    kanji: "消防士",
    meaning: "Petugas Pemadam Kebakaran",
    indonesian_translation_options: ["Petugas Pemadam Kebakaran"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gaka",
    furigana: "がか",
    kanji: "画家",
    meaning: "Pelukis",
    indonesian_translation_options: ["Pelukis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sakka",
    furigana: "さっか",
    kanji: "作家",
    meaning: "Penulis",
    indonesian_translation_options: ["Penulis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "engekika",
    furigana: "えんげきか",
    kanji: "演劇家",
    meaning: "Seniman Teater",
    indonesian_translation_options: ["Seniman Teater"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "seijika",
    furigana: "せいじか",
    kanji: "政治家",
    meaning: "Politisi",
    indonesian_translation_options: ["Politisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kōgaku-sha",
    furigana: "こうがくしゃ",
    kanji: "工学者",
    meaning: "Insinyur (akademis/penelitian)",
    indonesian_translation_options: ["Insinyur"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "jūi",
    furigana: "じゅうい",
    kanji: "獣医",
    meaning: "Dokter Hewan",
    indonesian_translation_options: ["Dokter Hewan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "zei-rishi",
    furigana: "ぜいりし",
    kanji: "税理士",
    meaning: "Konsultan Pajak",
    indonesian_translation_options: ["Konsultan Pajak"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "nōka",
    furigana: "のうか",
    kanji: "農家",
    meaning: "Petani",
    indonesian_translation_options: ["Petani"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "enge-nia",
    furigana: "エンジニア",
    kanji: "",
    meaning: "Insinyur, Teknisi",
    indonesian_translation_options: ["Insinyur", "Teknisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dezainā",
    furigana: "デザイナー",
    kanji: "",
    meaning: "Perancang, Desainer (umum)",
    indonesian_translation_options: ["Perancang", "Desainer"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "haiyuu",
    furigana: "はいゆう",
    kanji: "俳優",
    meaning: "Aktor, Aktris",
    indonesian_translation_options: ["Aktor", "Aktris"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kamera-man",
    furigana: "カメラマン",
    kanji: "",
    meaning: "Juru Kamera, Kameramen",
    indonesian_translation_options: ["Juru Kamera", "Kameramen"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kāpentaa",
    furigana: "カーペンター",
    kanji: "",
    meaning: "Tukang Kayu",
    indonesian_translation_options: ["Tukang Kayu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dentisuto",
    furigana: "デンティスト",
    kanji: "",
    meaning: "Dokter Gigi",
    indonesian_translation_options: ["Dokter Gigi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "eiga kantoku",
    furigana: "えいがかんとく",
    kanji: "映画監督",
    meaning: "Sutradara Film",
    indonesian_translation_options: ["Sutradara Film"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "supōtsu senshu",
    furigana: "スポーツせんしゅ",
    kanji: "スポーツ選手",
    meaning: "Atlet, Pemain Olahraga",
    indonesian_translation_options: ["Atlet", "Pemain Olahraga"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gakusha",
    furigana: "がくしゃ",
    kanji: "学者",
    meaning: "Ilmuwan, Cendekiawan",
    indonesian_translation_options: ["Ilmuwan", "Cendekiawan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shain",
    furigana: "しゃいん",
    kanji: "社員",
    meaning: "Pegawai (anggota perusahaan)",
    indonesian_translation_options: ["Pegawai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ueitā",
    furigana: "ウェイター",
    kanji: "",
    meaning: "Pelayan (pria), Pramusaji (pria)",
    indonesian_translation_options: ["Pelayan", "Pramusaji"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ueitoresu",
    furigana: "ウェイトレス",
    kanji: "",
    meaning: "Pelayan (wanita), Pramusaji (wanita)",
    indonesian_translation_options: ["Pelayan", "Pramusaji"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shōgyōka",
    furigana: "しょうぎょうか",
    kanji: "商業家",
    meaning: "Pengusaha, Pebisnis",
    indonesian_translation_options: ["Pengusaha", "Pebisnis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tetsudō-in",
    furigana: "てつどういん",
    kanji: "鉄道員",
    meaning: "Pegawai Kereta Api",
    indonesian_translation_options: ["Pegawai Kereta Api"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yūbinkyokuin",
    furigana: "ゆうびんきょくいん",
    kanji: "郵便局員",
    meaning: "Pegawai Kantor Pos",
    indonesian_translation_options: ["Pegawai Kantor Pos"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sensei",
    furigana: "せんせい",
    kanji: "先生",
    meaning: "Guru (digunakan sebagai sebutan kehormatan)",
    indonesian_translation_options: ["Guru"],
    canBeUsedInWaSentence: false,
  },
];

export const kataKerjaPart1 = [
  {
    romaji: "ikimasu",
    furigana: "いきます",
    kanji: "行きます",
    meaning: "to go",
    indonesian_translation_options: ["pergi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kimasu",
    furigana: "きます",
    kanji: "来ます",
    meaning: "to come",
    indonesian_translation_options: ["datang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaerimasu",
    furigana: "かえります",
    kanji: "帰ります",
    meaning: "to return / to go home",
    indonesian_translation_options: ["pulang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tabemasu",
    furigana: "たべます",
    kanji: "食べます",
    meaning: "to eat",
    indonesian_translation_options: ["makan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "nomimasu",
    furigana: "のみます",
    kanji: "飲みます",
    meaning: "to drink",
    indonesian_translation_options: ["minum"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "suimasu",
    furigana: "すいます",
    kanji: "吸います",
    meaning: "to inhale / to suck",
    indonesian_translation_options: ["menghisap"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "mimasu",
    furigana: "みます",
    kanji: "見ます",
    meaning: "to see / to watch",
    indonesian_translation_options: ["melihat", "menonton"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kikimasu",
    furigana: "ききます",
    kanji: "聞きます",
    meaning: "to listen / to hear",
    indonesian_translation_options: ["mendengar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tazunemasu",
    furigana: "たずねます",
    kanji: "尋ねます",
    meaning: "to ask / to inquire",
    indonesian_translation_options: ["bertanya"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yomimasu",
    furigana: "よみます",
    kanji: "読みます",
    meaning: "to read",
    indonesian_translation_options: ["membaca"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kakimasu",
    furigana: "かきます",
    kanji: "書きます",
    meaning: "to write / to draw",
    indonesian_translation_options: ["menulis", "menggambar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaimasu",
    furigana: "かいます",
    kanji: "買います",
    meaning: "to buy",
    indonesian_translation_options: ["membeli"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "torimasu",
    furigana: "とります",
    kanji: "撮ります",
    meaning: "to take (a photo)",
    indonesian_translation_options: ["mengambil (foto)"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsukurimasu",
    furigana: "つくります",
    kanji: "作ります",
    meaning: "to make / to do",
    indonesian_translation_options: ["mengerjakan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "aimasu",
    furigana: "あいます",
    kanji: "会います",
    meaning: "to meet",
    indonesian_translation_options: ["bertemu"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart2 = [
  {
    romaji: "kimemasu",
    furigana: "きります",
    kanji: "切ります",
    meaning: "to cut",
    indonesian_translation_options: ["memotong"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hasamimasu",
    furigana: "はさみます",
    kanji: "挟みます",
    meaning: "to clip / to pinch",
    indonesian_translation_options: ["menggunting"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "okurimasu",
    furigana: "おくります",
    kanji: "送ります",
    meaning: "to send",
    indonesian_translation_options: ["mengirim"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "agemasu",
    furigana: "あげます",
    kanji: "上げます",
    meaning: "to give",
    indonesian_translation_options: ["memberikan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "morimasu",
    furigana: "もらいます",
    kanji: "貰います",
    meaning: "to receive",
    indonesian_translation_options: ["menerima"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kashimasu",
    furigana: "かします",
    kanji: "貸します",
    meaning: "to lend",
    indonesian_translation_options: ["meminjamkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "karimasu",
    furigana: "かります",
    kanji: "借ります",
    meaning: "to borrow",
    indonesian_translation_options: ["meminjam"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "oshiemasu",
    furigana: "おしえます",
    kanji: "教えます",
    meaning: "to teach",
    indonesian_translation_options: ["mengajar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "benkyou shimasu",
    furigana: "べんきょうします",
    kanji: "勉強します",
    meaning: "to study / to learn",
    indonesian_translation_options: ["belajar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "denwa shimasu",
    furigana: "でんわします",
    kanji: "電話します",
    meaning: "to make a phone call",
    indonesian_translation_options: ["menelepon"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart3 = [
  {
    romaji: "imasu",
    furigana: "います",
    kanji: "います",
    meaning: "to have (a child / for living beings)",
    indonesian_translation_options: ["ada [anak]"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "arimasu",
    furigana: "あります",
    kanji: "あります",
    meaning: "to exist / to be located (for places, objects)",
    indonesian_translation_options: ["ada [di Jepang]"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kakarimasu",
    furigana: "かかります",
    kanji: "かかります",
    meaning: "to take (money, time) / to cost / to require",
    indonesian_translation_options: ["memakan atau perlu (uang/waktu)"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yasumimasu",
    furigana: "やすみます",
    kanji: "休みます",
    meaning: "to rest / to take a break",
    indonesian_translation_options: ["beristirahat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yasumimasu",
    furigana: "やすみます",
    kanji: "休みます",
    meaning: "to be absent from work / school",
    indonesian_translation_options: ["tidak masuk [kerja]"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "asobimasu",
    furigana: "あそびます",
    kanji: "遊びます",
    meaning: "to play / to have fun",
    indonesian_translation_options: ["bermain"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "oyogimasu",
    furigana: "およぎます",
    kanji: "泳ぎます",
    meaning: "to swim",
    indonesian_translation_options: ["berenang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "mukemasu",
    furigana: "むかえます",
    kanji: "迎えます",
    meaning: "to pick up / to welcome",
    indonesian_translation_options: ["menjemput"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsukaremasu",
    furigana: "つかれます",
    kanji: "疲れます",
    meaning: "to get tired",
    indonesian_translation_options: ["lelah"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kekkon shimasu",
    furigana: "けっこんします",
    kanji: "結婚します",
    meaning: "to get married",
    indonesian_translation_options: ["menikah"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaimono shimasu",
    furigana: "かいものします",
    kanji: "買い物します",
    meaning: "to shop / to go shopping",
    indonesian_translation_options: ["berbelanja"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart4 = [
  {
    romaji: "tsukemasu",
    furigana: "つけます",
    kanji: "付けます",
    meaning: "to turn on / to switch on / to attach",
    indonesian_translation_options: ["menyalakan", "memasang", "menghidupkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "keshimasu",
    furigana: "けします",
    kanji: "消します",
    meaning: "to turn off / to extinguish",
    indonesian_translation_options: ["mematikan", "memadamkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "akemasu",
    furigana: "あけます",
    kanji: "開けます",
    meaning: "to open",
    indonesian_translation_options: ["membuka"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shimemasu",
    furigana: "しめます",
    kanji: "閉めます",
    meaning: "to close",
    indonesian_translation_options: ["menutup"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "isogimasu",
    furigana: "いそぎます",
    kanji: "急ぎます",
    meaning: "to hurry",
    indonesian_translation_options: ["buru-buru"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "machimasu",
    furigana: "まちます",
    kanji: "待ちます",
    meaning: "to wait",
    indonesian_translation_options: ["menunggu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hakobimasu",
    furigana: "はこびます",
    kanji: "運びます",
    meaning: "to carry / to bring",
    indonesian_translation_options: ["membawa"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "torimasu",
    furigana: "とります",
    kanji: "取ります",
    meaning: "to take / to pick up",
    indonesian_translation_options: ["mengambil"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tasukemasu",
    furigana: "たすけます",
    kanji: "助けます",
    meaning: "to help / to assist",
    indonesian_translation_options: ["membantu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hanashimasu",
    furigana: "はなします",
    kanji: "話します",
    meaning: "to speak / to talk",
    indonesian_translation_options: ["berbicara"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsukemasu",
    furigana: "つけます",
    kanji: "着けます",
    meaning: "to put on / to wear (accessory, clothes)",
    indonesian_translation_options: ["memakai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tomemasu",
    furigana: "とめます",
    kanji: "止めます",
    meaning: "to stop / to park",
    indonesian_translation_options: ["menghentikan", "memarkir"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "misemasu",
    furigana: "みせます",
    kanji: "見せます",
    meaning: "to show",
    indonesian_translation_options: ["memperlihatkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "oshiemasu",
    furigana: "おしえます",
    kanji: "教えます",
    meaning: "to tell / to inform (address, info)",
    indonesian_translation_options: ["memberitahukan alamat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "suwarimasu",
    furigana: "すわります",
    kanji: "座ります",
    meaning: "to sit",
    indonesian_translation_options: ["duduk"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tachimasu",
    furigana: "たちます",
    kanji: "立ちます",
    meaning: "to stand",
    indonesian_translation_options: ["berdiri"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hairimasu",
    furigana: "はいります",
    kanji: "入ります",
    meaning: "to enter",
    indonesian_translation_options: ["masuk"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "demasu",
    furigana: "でます",
    kanji: "出ます",
    meaning: "to exit / to leave",
    indonesian_translation_options: ["keluar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kissaten ni hairimasu",
    furigana: "きっさてんにはいります",
    kanji: "喫茶店に入ります",
    meaning: "to enter a coffee shop",
    indonesian_translation_options: ["masuk ke coffee shop"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kissaten o demasu",
    furigana: "きっさてんをでます",
    kanji: "喫茶店を出ます",
    meaning: "to leave a coffee shop",
    indonesian_translation_options: ["keluar dari coffee shop"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ame ga furimasu",
    furigana: "あめがふります",
    kanji: "雨が降ります",
    meaning: "it rains",
    indonesian_translation_options: ["turun hujan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kopii shimasu",
    furigana: "コピーします",
    kanji: "コピーします",
    meaning: "to photocopy",
    indonesian_translation_options: ["memfotokopi"],
    canBeUsedInWaSentence: true,
  },
];
export const kataKerjaPart5 = [
  {
    romaji: "okimasu",
    furigana: "おきます",
    kanji: "置きます",
    meaning: "to put / to place / to set down",
    indonesian_translation_options: ["meletakkan", "menaruh"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsukurimasu",
    furigana: "つくります",
    kanji: "作ります",
    meaning: "to make / to produce / to build",
    indonesian_translation_options: ["membuat", "memproduksi", "membangun"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "urimasu",
    furigana: "うります",
    kanji: "売ります",
    meaning: "to sell",
    indonesian_translation_options: ["menjual"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shirimasu",
    furigana: "しります",
    kanji: "知ります",
    meaning: "to know / to get to know",
    indonesian_translation_options: ["mengetahui", "mengenal"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sundemasu",
    furigana: "すんでいます",
    kanji: "住んでいます",
    meaning: "to live / to reside",
    indonesian_translation_options: ["tinggal"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kenkyuu shimasu",
    furigana: "けんきゅうします",
    kanji: "研究します",
    meaning: "to research / to study",
    indonesian_translation_options: ["meneliti"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart6 = [
  {
    romaji: "densha ni norimasu",
    furigana: "でんしゃにのります",
    kanji: "電車に乗ります",
    meaning: "to ride / get on an electric train",
    indonesian_translation_options: ["naik kereta rel listrik"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "densha o orimasu",
    furigana: "でんしゃをおります",
    kanji: "電車を降ります",
    meaning: "to get off / get down from an electric train",
    indonesian_translation_options: ["turun kereta rel listrik"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "norikaemasu",
    furigana: "のりかえます",
    kanji: "乗り換えます",
    meaning: "to transfer / to change trains or buses",
    indonesian_translation_options: ["ganti", "pindah"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ofuroni hairimasu",
    furigana: "おふろにはいります",
    kanji: "お風呂に入ります",
    meaning: "to take a bath / to bathe",
    indonesian_translation_options: ["mandi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "mazemasu",
    furigana: "まぜます",
    kanji: "混ぜます",
    meaning: "to mix / to blend",
    indonesian_translation_options: ["memadukan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dashimasu",
    furigana: "だします",
    kanji: "出します",
    meaning: "to put out / to hand over / to send",
    indonesian_translation_options: ["mengeluarkan", "menyerahkan", "mengirim"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "okane o torimasu",
    furigana: "おかねをとります",
    kanji: "お金を取ります",
    meaning: "to take out money / withdraw money",
    indonesian_translation_options: ["mengeluarkan / mengambil uang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "daigaku ni hairimasu",
    furigana: "だいがくにはいります",
    kanji: "大学に入ります",
    meaning: "to enter a university",
    indonesian_translation_options: ["masuk universitas"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "daigaku o demasu",
    furigana: "だいがくをでます",
    kanji: "大学を出ます",
    meaning: "to graduate from university",
    indonesian_translation_options: ["tamat dari universitas"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "oshimasu",
    furigana: "おします",
    kanji: "押します",
    meaning: "to push / to press",
    indonesian_translation_options: ["menekan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "osake o nomimasu",
    furigana: "おさけをのみます",
    kanji: "お酒を飲みます",
    meaning: "to drink alcoholic beverages",
    indonesian_translation_options: ["meminum minuman keras"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hajimemasu",
    furigana: "はじめます",
    kanji: "始めます",
    meaning: "to start / to begin",
    indonesian_translation_options: ["mulai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "otozuremasu",
    furigana: "訪れます",
    kanji: "訪れます",
    meaning: "to visit",
    indonesian_translation_options: ["mengunjungi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "denwa shimasu",
    furigana: "でんわします",
    kanji: "電話します",
    meaning: "to call / to phone",
    indonesian_translation_options: ["menelepon"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart7 = [
  {
    romaji: "oboemasu",
    furigana: "おぼえます",
    kanji: "覚えます",
    meaning: "to memorize / to remember",
    indonesian_translation_options: ["mengingat", "menghafal"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kegashimasu",
    furigana: "けがします",
    kanji: "怪我します",
    meaning: "to get injured",
    indonesian_translation_options: ["luka"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ushinai masu",
    furigana: "うしないます",
    kanji: "失います",
    meaning: "to lose (something)",
    indonesian_translation_options: ["kehilangan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "haraimasu",
    furigana: "はらいます",
    kanji: "払います",
    meaning: "to pay",
    indonesian_translation_options: ["membayar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaeshimasu",
    furigana: "かえします",
    kanji: "返します",
    meaning: "to return (something)",
    indonesian_translation_options: ["mengembalikan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dekakemasu",
    furigana: "でかけます",
    kanji: "出かけます",
    meaning: "to go out / to leave / to depart",
    indonesian_translation_options: ["pergi", "keluar", "berangkat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "nugimasu",
    furigana: "ぬぎます",
    kanji: "脱ぎます",
    meaning: "to take off (clothes, shoes, etc.)",
    indonesian_translation_options: [
      "buka baju / sepatu dll",
      "membawa pergi (pakaian)",
    ],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "motte kimasu",
    furigana: "もってきます",
    kanji: "持って来ます",
    meaning: "to bring (something to here)",
    indonesian_translation_options: ["membawa datang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shinpai shimasu",
    furigana: "しんぱいします",
    kanji: "心配します",
    meaning: "to worry",
    indonesian_translation_options: ["mengkhawatirkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "zangyou shimasu",
    furigana: "ざんぎょうします",
    kanji: "残業します",
    meaning: "to do overtime work",
    indonesian_translation_options: ["melembur"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shucchou shimasu",
    furigana: "しゅっちょうします",
    kanji: "出張します",
    meaning: "to go on a business trip",
    indonesian_translation_options: ["dinas"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kusuri o nomimasu",
    furigana: "くすりをのみます",
    kanji: "薬を飲みます",
    meaning: "to take medicine",
    indonesian_translation_options: ["minum obat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ofuro ni hairimasu",
    furigana: "おふろにはいります",
    kanji: "お風呂に入ります",
    meaning: "to bathe / to enter a bath",
    indonesian_translation_options: ["mandi", "masuk ofuro"],
    canBeUsedInWaSentence: true,
  },
];

export const kataKerjaPart8 = [
  {
    romaji: "dekimasu",
    furigana: "できます",
    kanji: "出来ます",
    meaning: "to be able to / can / to be capable of",
    indonesian_translation_options: ["dapat", "bisa", "mampu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "araimasu",
    furigana: "あらいます",
    kanji: "洗います",
    meaning: "to wash",
    indonesian_translation_options: ["mencuci"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "himasu",
    furigana: "ひきます",
    kanji: "弾きます",
    meaning: "to play a musical instrument",
    indonesian_translation_options: ["bermain (alat musik)"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "utaimasu",
    furigana: "うたいます",
    kanji: "歌います",
    meaning: "to sing",
    indonesian_translation_options: ["bernyanyi", "menyanyi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "atsumemasu",
    furigana: "あつめます",
    kanji: "集めます",
    meaning: "to collect / to gather",
    indonesian_translation_options: ["mengumpulkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sutemasu",
    furigana: "すてます",
    kanji: "捨てます",
    meaning: "to throw away / to discard",
    indonesian_translation_options: ["membuang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaemasu",
    furigana: "かえます",
    kanji: "換えます",
    meaning: "to change / to exchange",
    indonesian_translation_options: ["mengganti", "menukar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "unten shimasu",
    furigana: "うんてんします",
    kanji: "運転します",
    meaning: "to drive / to operate a vehicle",
    indonesian_translation_options: ["menyetir", "mengendarai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "chuumon shimasu",
    furigana: "ちゅうもんします",
    kanji: "注文します",
    meaning: "to order (food, goods, etc.)",
    indonesian_translation_options: ["memesan"],
    canBeUsedInWaSentence: true,
  },
];

const kataKerjaPart9 = [
  {
    romaji: "norimasu",
    furigana: "のります",
    kanji: "乗ります",
    meaning: "to ride / to get on",
    indonesian_translation_options: ["naik"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hoteru ni tomarimasu",
    furigana: "ホテルにとまります",
    kanji: "ホテルに泊まります",
    meaning: "to stay at a hotel",
    indonesian_translation_options: ["menginap di hotel"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "soujishimasu",
    furigana: "そうじします",
    kanji: "掃除します",
    meaning: "to clean",
    indonesian_translation_options: ["membersihkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sentakushimasu",
    furigana: "せんたくします",
    kanji: "洗濯します",
    meaning: "to do laundry / to wash clothes",
    indonesian_translation_options: ["mencuci pakaian"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ninarimasu",
    furigana: "なります",
    kanji: "なります",
    meaning: "to become",
    indonesian_translation_options: ["menjadi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "biza ga irimasu",
    furigana: "ビザがいります",
    kanji: "ビザが要ります",
    meaning: "to need a visa",
    indonesian_translation_options: ["memerlukan visa"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shirabemasu",
    furigana: "しらべます",
    kanji: "調べます",
    meaning: "to check / to examine / to investigate",
    indonesian_translation_options: ["memeriksa", "meneliti", "mengecek"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "naoshimasu",
    furigana: "なおします",
    kanji: "直します",
    meaning: "to fix / to repair",
    indonesian_translation_options: ["memperbaiki"],
    canBeUsedInWaSentence: true,
  },
];

const kataKerjaPart10 = [
  {
    romaji: "omoimasu",
    furigana: "思います",
    kanji: "思います",
    meaning: "to think / to consider / to believe",
    indonesian_translation_options: ["mengira", "berpikir"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "iimasu",
    furigana: "言います",
    kanji: "言います",
    meaning: "to say / to tell",
    indonesian_translation_options: ["mengatakan", "berkata"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kachimasu",
    furigana: "勝ちます",
    kanji: "勝ちます",
    meaning: "to win",
    indonesian_translation_options: ["menang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "makemasu",
    furigana: "負けます",
    kanji: "負けます",
    meaning: "to lose",
    indonesian_translation_options: ["kalah"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "paatii ga arimasu",
    furigana: "パーティーがあります",
    kanji: "パーティーがあります",
    meaning: "a party is held / there is a party",
    indonesian_translation_options: ["diadakan pesta"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yakunitachimasu",
    furigana: "役に立ちます",
    kanji: "役に立ちます",
    meaning: "to be useful / to be helpful",
    indonesian_translation_options: ["berguna", "bermanfaat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hikkoshimasu",
    furigana: "引っ越します",
    kanji: "引っ越します",
    meaning: "to move (residence)",
    indonesian_translation_options: ["pindah", "bergerak"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yameru",
    furigana: "やめます",
    kanji: "辞めます",
    meaning: "to quit / to resign from work",
    indonesian_translation_options: ["berhenti kerja"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ki o tsukemasu",
    furigana: "気をつけます",
    kanji: "気をつけます",
    meaning: "to be careful / to watch out / to pay attention",
    indonesian_translation_options: ["berwaspada", "berhati-hati"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ryuugaku shimasu",
    furigana: "留学します",
    kanji: "留学します",
    meaning: "to study abroad",
    indonesian_translation_options: ["studi di luar negeri"],
    canBeUsedInWaSentence: true,
  },
];

const kataKerjaPart11 = [
  {
    romaji: "shatsu o kimasu",
    furigana: "シャツをきます",
    kanji: "シャツを着ます",
    meaning: "to wear a shirt",
    indonesian_translation_options: ["memakai kemeja"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kutsu / zubon o hakimasu",
    furigana: "くつ/ズボンをはきます",
    kanji: "靴／ズボンを履きます",
    meaning: "to wear shoes / pants",
    indonesian_translation_options: ["memakai sepatu / celana"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "boushi o kaburimasu",
    furigana: "ぼうしをかぶります",
    kanji: "帽子をかぶります",
    meaning: "to wear a hat",
    indonesian_translation_options: ["memakai topi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "megane o kakemasu",
    furigana: "めがねをかけます",
    kanji: "眼鏡をかけます",
    meaning: "to wear glasses",
    indonesian_translation_options: ["memakai kaca mata"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "necktie o shimasu",
    furigana: "ネクタイをします",
    kanji: "ネクタイをします",
    meaning: "to wear a tie",
    indonesian_translation_options: ["memakai dasi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "umaremasu",
    furigana: "うまれます",
    kanji: "生まれます",
    meaning: "to be born",
    indonesian_translation_options: ["lahir"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shinimasu",
    furigana: "しにます",
    kanji: "死にます",
    meaning: "to die",
    indonesian_translation_options: ["meninggal"],
    canBeUsedInWaSentence: true,
  },
];

const kataKerjaPart12 = [
  {
    romaji: "sensei ni kikimasu",
    furigana: "先生に聞きます",
    kanji: "先生に聞きます",
    meaning: "to ask a teacher",
    indonesian_translation_options: ["bertanya kepada guru"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "mawarimasu",
    furigana: "回ります",
    kanji: "回ります",
    meaning: "to turn / rotate",
    indonesian_translation_options: ["memutar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hikimasu",
    furigana: "引きます",
    kanji: "引きます",
    meaning: "to pull",
    indonesian_translation_options: ["tarik"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaemasu",
    furigana: "変えます",
    kanji: "変えます",
    meaning: "to change / to alter",
    indonesian_translation_options: ["mengubah"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sawari-masu",
    furigana: "触ります",
    kanji: "触ります",
    meaning: "to touch",
    indonesian_translation_options: ["menyentuh"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "doa ni sawarimasu",
    furigana: "ドアに触ります",
    kanji: "ドアに触ります",
    meaning: "to touch the door",
    indonesian_translation_options: ["menyentuh pintu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "otsuri ga demasu",
    furigana: "お釣りが出ます",
    kanji: "お釣りが出ます",
    meaning: "change comes out / to get change",
    indonesian_translation_options: ["keluar uang kembalian"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "arukimasu",
    furigana: "歩きます",
    kanji: "歩きます",
    meaning: "to walk",
    indonesian_translation_options: ["berjalan kaki"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "hashi o watarimasu",
    furigana: "橋を渡ります",
    kanji: "橋を渡ります",
    meaning: "to cross a bridge",
    indonesian_translation_options: ["menyebrang jembatan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "watarimasu",
    furigana: "渡ります",
    kanji: "渡ります",
    meaning: "to cross",
    indonesian_translation_options: ["menyebrang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "magarimasu",
    furigana: "曲がります",
    kanji: "曲がります",
    meaning: "to turn",
    indonesian_translation_options: ["belok"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "migi ni magarimasu",
    furigana: "右に曲がります",
    kanji: "右に曲がります",
    meaning: "to turn right",
    indonesian_translation_options: ["belok ke kanan"],
    canBeUsedInWaSentence: true,
  },
];

const kataKerjaPart13 = [
  {
    romaji: "agemasu",
    furigana: "あげます",
    kanji: "あげます",
    meaning: "to give / to present",
    indonesian_translation_options: ["diberikan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "naoshimasu",
    furigana: "直します",
    kanji: "直します",
    meaning: "to correct / to fix",
    indonesian_translation_options: ["mengoreksi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsurete ikimasu",
    furigana: "連れて行きます",
    kanji: "連れて行きます",
    meaning: "to take someone (to go)",
    indonesian_translation_options: ["membawa / mengajak pergi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsurete kimasu",
    furigana: "連れて来ます",
    kanji: "連れて来ます",
    meaning: "to bring someone (to come)",
    indonesian_translation_options: ["membawa datang / mengajak datang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "okurimasu",
    furigana: "送ります",
    kanji: "送ります",
    meaning: "to escort / to send off",
    indonesian_translation_options: ["mengantar orang"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shoukai shimasu",
    furigana: "紹介します",
    kanji: "紹介します",
    meaning: "to introduce",
    indonesian_translation_options: ["memperkenalkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "todokemasu",
    furigana: "届けます",
    kanji: "届けます",
    meaning: "to deliver / to send / to bring",
    indonesian_translation_options: ["mengantarkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "setsumei shimasu",
    furigana: "説明します",
    kanji: "説明します",
    meaning: "to explain",
    indonesian_translation_options: ["menjelaskan", "menerangkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kangaemasu",
    furigana: "考えます",
    kanji: "考えます",
    meaning: "to think / to consider",
    indonesian_translation_options: ["berpikir", "memikirkan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tsukimasu",
    furigana: "着きます",
    kanji: "着きます",
    meaning: "to arrive",
    indonesian_translation_options: ["tiba", "sampai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "toshio torimasu",
    furigana: "年を取ります",
    kanji: "年を取ります",
    meaning: "to get older / to age",
    indonesian_translation_options: ["berumur", "lanjut usia"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tarimasu",
    furigana: "足ります",
    kanji: "足ります",
    meaning: "to be sufficient / enough",
    indonesian_translation_options: ["cukup"],
    canBeUsedInWaSentence: true,
  },
];
