const countries = [
  {
    "Country (Indonesian)": "Amerika Serikat",
    "Country (Japanese)": "アメリカ",
    "Country (Kanji)": "",
    "Person (Japanese)": "アメリカ人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Inggris",
    "Country (Japanese)": "イギリス",
    "Country (Kanji)": "",
    "Person (Japanese)": "イギリス人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Italia",
    "Country (Japanese)": "イタリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "イタリア人",
    "Language (Japanese)": "イタリア語",
  },
  {
    "Country (Indonesian)": "Iran",
    "Country (Japanese)": "イラン",
    "Country (Kanji)": "",
    "Person (Japanese)": "イラン人",
    "Language (Japanese)": "ペルシア語",
  },
  {
    "Country (Indonesian)": "India",
    "Country (Japanese)": "インド",
    "Country (Kanji)": "",
    "Person (Japanese)": "インド人",
    "Language (Japanese)": "ヒンディー語",
  },
  {
    "Country (Indonesian)": "Indonesia",
    "Country (Japanese)": "インドネシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "インドネシア人",
    "Language (Japanese)": "インドネシア語",
  },
  {
    "Country (Indonesian)": "Mesir",
    "Country (Japanese)": "エジプト",
    "Country (Kanji)": "",
    "Person (Japanese)": "エジプト人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Australia",
    "Country (Japanese)": "オーストラリア",
    "Country (Kanji)": "",
    "Person (Japanese)": "オーストラリア人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Kanada",
    "Country (Japanese)": "カナダ",
    "Country (Kanji)": "",
    "Person (Japanese)": "カナダ人",
    "Language (Japanese)": "えいご, フランス語",
  },
  {
    "Country (Indonesian)": "Korea Selatan",
    "Country (Japanese)": "かんこく",
    "Country (Kanji)": "韓国",
    "Person (Japanese)": "かんこく人",
    "Language (Japanese)": "かんこく語",
  },
  {
    "Country (Indonesian)": "Arab Saudi",
    "Country (Japanese)": "サウジアラビア",
    "Country (Kanji)": "",
    "Person (Japanese)": "サウジアラビア人",
    "Language (Japanese)": "アラビア語",
  },
  {
    "Country (Indonesian)": "Singapura",
    "Country (Japanese)": "シンガポール",
    "Country (Kanji)": "",
    "Person (Japanese)": "シンガポール人",
    "Language (Japanese)": "えいご",
  },
  {
    "Country (Indonesian)": "Spanyol",
    "Country (Japanese)": "スペイン",
    "Country (Kanji)": "",
    "Person (Japanese)": "スペイン人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Thailand",
    "Country (Japanese)": "タイ",
    "Country (Kanji)": "",
    "Person (Japanese)": "タイ人",
    "Language (Japanese)": "タイ語",
  },
  {
    "Country (Indonesian)": "Cina",
    "Country (Japanese)": "ちゅうごく",
    "Country (Kanji)": "中国",
    "Person (Japanese)": "ちゅうごく人",
    "Language (Japanese)": "ちゅうごく語",
  },
  {
    "Country (Indonesian)": "Jerman",
    "Country (Japanese)": "ドイツ",
    "Country (Kanji)": "",
    "Person (Japanese)": "ドイツ人",
    "Language (Japanese)": "ドイツ語",
  },
  {
    "Country (Indonesian)": "Jepang",
    "Country (Japanese)": "にほん",
    "Country (Kanji)": "日本",
    "Person (Japanese)": "にほん人",
    "Language (Japanese)": "にほんご",
  },
  {
    "Country (Indonesian)": "Perancis",
    "Country (Japanese)": "フランス",
    "Country (Kanji)": "",
    "Person (Japanese)": "フランス人",
    "Language (Japanese)": "フランス語",
  },
  {
    "Country (Indonesian)": "Filipina",
    "Country (Japanese)": "フィリピン",
    "Country (Kanji)": "",
    "Person (Japanese)": "フィリピン人",
    "Language (Japanese)": "フィリピノ語",
  },
  {
    "Country (Indonesian)": "Brazil",
    "Country (Japanese)": "ブラジル",
    "Country (Kanji)": "",
    "Person (Japanese)": "ブラジル人",
    "Language (Japanese)": "ポルトガル語",
  },
  {
    "Country (Indonesian)": "Vietnam",
    "Country (Japanese)": "ベトナム",
    "Country (Kanji)": "",
    "Person (Japanese)": "ベトナム人",
    "Language (Japanese)": "ベトナム語",
  },
  {
    "Country (Indonesian)": "Malaysia",
    "Country (Japanese)": "マレーシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "マレーシア人",
    "Language (Japanese)": "マレーシア語",
  },
  {
    "Country (Indonesian)": "Meksiko",
    "Country (Japanese)": "メキシコ",
    "Country (Kanji)": "",
    "Person (Japanese)": "メキシコ人",
    "Language (Japanese)": "スペイン語",
  },
  {
    "Country (Indonesian)": "Rusia",
    "Country (Japanese)": "ロシア",
    "Country (Kanji)": "",
    "Person (Japanese)": "ロシア人",
    "Language (Japanese)": "ロシア語",
  },
];

export const occupations = [
  {
    romaji: "kyoushi",
    furigana: "きょうし",
    kanji: "教師",
    meaning: "Guru, Dosen (sebagai profesi)",
    indonesian_translation_options: ["Guru", "Dosen"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gakusei",
    furigana: "がくせい",
    kanji: "学生",
    meaning: "Mahasiswa, Pelajar",
    indonesian_translation_options: ["Mahasiswa", "Pelajar"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kaishain",
    furigana: "かいしゃいん",
    kanji: "会社員",
    meaning: "Karyawan Perusahaan",
    indonesian_translation_options: ["Karyawan Perusahaan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ginkouin",
    furigana: "ぎんこういん",
    kanji: "銀行員",
    meaning: "Pegawai Bank",
    indonesian_translation_options: ["Pegawai Bank"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "isha",
    furigana: "いしゃ",
    kanji: "医者",
    meaning: "Dokter",
    indonesian_translation_options: ["Dokter"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kenkyuusha",
    furigana: "けんきゅうしゃ",
    kanji: "研究者",
    meaning: "Peneliti",
    indonesian_translation_options: ["Peneliti"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shufu",
    furigana: "しゅふ",
    kanji: "主婦",
    meaning: "Ibu Rumah Tangga",
    indonesian_translation_options: ["Ibu Rumah Tangga"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kōmuin",
    furigana: "こうむいん",
    kanji: "公務員",
    meaning: "Pegawai Negeri Sipil (PNS)",
    indonesian_translation_options: ["Pegawai Negeri Sipil"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "bengoshi",
    furigana: "べんごし",
    kanji: "弁護士",
    meaning: "Pengacara",
    indonesian_translation_options: ["Pengacara"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kangoshi",
    furigana: "かんごし",
    kanji: "看護師",
    meaning: "Perawat",
    indonesian_translation_options: ["Perawat"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sekkeishi",
    furigana: "せっけいし",
    kanji: "設計士",
    meaning: "Arsitek, Desainer (bidang bangunan/teknik)",
    indonesian_translation_options: ["Arsitek", "Desainer"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "keisatsukan",
    furigana: "けいさつかん",
    kanji: "警察官",
    meaning: "Polisi",
    indonesian_translation_options: ["Polisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ten'in",
    furigana: "てんいん",
    kanji: "店員",
    meaning: "Pegawai Toko",
    indonesian_translation_options: ["Pegawai Toko"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "unten-shu",
    furigana: "うんてんしゅ",
    kanji: "運転手",
    meaning: "Pengemudi, Sopir",
    indonesian_translation_options: ["Pengemudi", "Sopir"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ryōrinin",
    furigana: "りょうりにん",
    kanji: "料理人",
    meaning: "Juru Masak, Koki",
    indonesian_translation_options: ["Juru Masak", "Koki"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shōbōshi",
    furigana: "しょうぼうし",
    kanji: "消防士",
    meaning: "Petugas Pemadam Kebakaran",
    indonesian_translation_options: ["Petugas Pemadam Kebakaran"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gaka",
    furigana: "がか",
    kanji: "画家",
    meaning: "Pelukis",
    indonesian_translation_options: ["Pelukis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sakka",
    furigana: "さっか",
    kanji: "作家",
    meaning: "Penulis",
    indonesian_translation_options: ["Penulis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "engekika",
    furigana: "えんげきか",
    kanji: "演劇家",
    meaning: "Seniman Teater",
    indonesian_translation_options: ["Seniman Teater"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "seijika",
    furigana: "せいじか",
    kanji: "政治家",
    meaning: "Politisi",
    indonesian_translation_options: ["Politisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kōgaku-sha",
    furigana: "こうがくしゃ",
    kanji: "工学者",
    meaning: "Insinyur (akademis/penelitian)",
    indonesian_translation_options: ["Insinyur"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "jūi",
    furigana: "じゅうい",
    kanji: "獣医",
    meaning: "Dokter Hewan",
    indonesian_translation_options: ["Dokter Hewan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "zei-rishi",
    furigana: "ぜいりし",
    kanji: "税理士",
    meaning: "Konsultan Pajak",
    indonesian_translation_options: ["Konsultan Pajak"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "nōka",
    furigana: "のうか",
    kanji: "農家",
    meaning: "Petani",
    indonesian_translation_options: ["Petani"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "enge-nia",
    furigana: "エンジニア",
    kanji: "",
    meaning: "Insinyur, Teknisi",
    indonesian_translation_options: ["Insinyur", "Teknisi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dezainā",
    furigana: "デザイナー",
    kanji: "",
    meaning: "Perancang, Desainer (umum)",
    indonesian_translation_options: ["Perancang", "Desainer"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "haiyuu",
    furigana: "はいゆう",
    kanji: "俳優",
    meaning: "Aktor, Aktris",
    indonesian_translation_options: ["Aktor", "Aktris"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kamera-man",
    furigana: "カメラマン",
    kanji: "",
    meaning: "Juru Kamera, Kameramen",
    indonesian_translation_options: ["Juru Kamera", "Kameramen"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "kāpentaa",
    furigana: "カーペンター",
    kanji: "",
    meaning: "Tukang Kayu",
    indonesian_translation_options: ["Tukang Kayu"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "dentisuto",
    furigana: "デンティスト",
    kanji: "",
    meaning: "Dokter Gigi",
    indonesian_translation_options: ["Dokter Gigi"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "eiga kantoku",
    furigana: "えいがかんとく",
    kanji: "映画監督",
    meaning: "Sutradara Film",
    indonesian_translation_options: ["Sutradara Film"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "supōtsu senshu",
    furigana: "スポーツせんしゅ",
    kanji: "スポーツ選手",
    meaning: "Atlet, Pemain Olahraga",
    indonesian_translation_options: ["Atlet", "Pemain Olahraga"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "gakusha",
    furigana: "がくしゃ",
    kanji: "学者",
    meaning: "Ilmuwan, Cendekiawan",
    indonesian_translation_options: ["Ilmuwan", "Cendekiawan"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shain",
    furigana: "しゃいん",
    kanji: "社員",
    meaning: "Pegawai (anggota perusahaan)",
    indonesian_translation_options: ["Pegawai"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ueitā",
    furigana: "ウェイター",
    kanji: "",
    meaning: "Pelayan (pria), Pramusaji (pria)",
    indonesian_translation_options: ["Pelayan", "Pramusaji"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "ueitoresu",
    furigana: "ウェイトレス",
    kanji: "",
    meaning: "Pelayan (wanita), Pramusaji (wanita)",
    indonesian_translation_options: ["Pelayan", "Pramusaji"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "shōgyōka",
    furigana: "しょうぎょうか",
    kanji: "商業家",
    meaning: "Pengusaha, Pebisnis",
    indonesian_translation_options: ["Pengusaha", "Pebisnis"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "tetsudō-in",
    furigana: "てつどういん",
    kanji: "鉄道員",
    meaning: "Pegawai Kereta Api",
    indonesian_translation_options: ["Pegawai Kereta Api"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "yūbinkyokuin",
    furigana: "ゆうびんきょくいん",
    kanji: "郵便局員",
    meaning: "Pegawai Kantor Pos",
    indonesian_translation_options: ["Pegawai Kantor Pos"],
    canBeUsedInWaSentence: true,
  },
  {
    romaji: "sensei",
    furigana: "せんせい",
    kanji: "先生",
    meaning: "Guru (digunakan sebagai sebutan kehormatan)",
    indonesian_translation_options: ["Guru"],
    canBeUsedInWaSentence: false,
  },
];
